### PR TITLE
[#13] Fix errors `loadMoreItems` not work if rerendering runs before the promise resolves

### LINKED ISSUE #13: Fix errors `loadMoreItems` not work if rerendering runs before the promise resolves
If updating `data` and rerendering runs before `loadMoreItems`'s promise resolves, we have this problem
where the new data are not rerendered because rerendering has run already.

```ts
const loadMoreItems = async () => {
  if(cache.get(data.length)) {
    // In this branch loadMoreItems is async but updates data instantly!
    setData(data => [...data, cache.get(data.length)]); 
  } else {
    setData(data => [...data, await api()]);
  }
}
```

Even if `pending.current` is the one which can fix the issue by deleting itself, if I delete it from the source code, the problem would go away,
It is needed to prevent excessive `loadMoreItems` calls.

Add a dummy `state` into `InfiniteScroll` component to change the value.
Do not directly subscribe to `data` changes but dummy state changes.

```tsx
const [dummy, setDummy] = useState(0);

const loadMoreItems = useCallback(() => {
  ...
  const ret = loadMoreItems(direction);
  if (isPromise(ret)) {
    await ret;
  }
  setDummy((dummy) => dummy + 1);
  pending.current = false;
  ...
  }, [...]);

  useEffect(() =>{
    ...
  }, [dummy, ...]);
```

However, the `useEffect` still need to depend on `data` to do `isItemLoaded(data.length)`.
~But, maybe we can depend on `data?.length`...~
~If `data` does change but `data.length` remains still, the `useEffect` will not run, but doesn't it count into an **edge case**?~
Not only the component can update `data` by calling `loadMoreItems` but also codes outside the component may update `data`. Thus it would be best to leave `data` inside the deps.

Also, if the provided `loadMoreItems` finished earlier than `data` changes (e.g. callback pattern)
~there can be an another issue where because `useEffect` runs before `data` actually changes.~
If I includes `data` inside `useEffect` deps, there is no problem since it will call `loadMoreItems` upon `data` changes.

### PR DESCRIPTION
**Pull request by dlguswo333**
closes #13.

### CODE REVIEW

File: package/src/InfiniteScroll.tsx [hunk 1]
```diff
@@ -56,12 +56,15 @@ const InfiniteScroll = ({
...
+  /** A dummy state to trigger rerender when promises by `loadMoreItems` resolves. */
+  const [dummyState, setDummyState] = useState(0);
+  const forceRerender = () => setDummyState(pre => pre + 1);
   /**
    * Prevent calling `loadMoreItems` frequently when loading items at the start.
    * However, do this only if enough items are loaded that
    * the `outerRef`'s scrollHeight is large enough to scroll the element.
    */
-  const shouldBlockLoadMoreItems = useRef<number | null>(null);
+  const shouldBlockLoadMoreItems = useRef<ReturnType<typeof setTimeout> | null>(null);
```
Comment (dlguswo333) [inline package/src/InfiniteScroll.tsx:67]: This is to prevent TS type erros when `@types/node` gets injected.
